# Config format schema number
format_version: 1

###################
## Model options
model_params:
  model_architecture: "largekernelseg"

  input_dims: 13
  spatial_shape:
    - 2000
    - 2000
    - 120
  scale_list:
    - 2
    - 4
    # - 8
    # - 16
  hiden_size: 8
  num_classes: 2
  large_kernel_size:
    - 3 # TODO: was 9, maybe set to 3
    - 3
    - 3
  spatial_group_partition:
    - 0
    - 3
    - 6
    - 9
  model_load_path: "output_skitti/opensource_9ks_s030_w64_0.pt"
  model_save_path: "output_skitti/opensource_9ks_s030_w64_.pt"

###################
## Dataset options
dataset_params:
  training_size: 19130
  dataset_type: "point_semkitti_mix"
  pc_dataset_type: "SemKITTI_sk"
  collate_type: "mix_collate_fn_default"
  ignore_label: 255
  label_mapping: "./config/label_mapping/semantic-kitti-sub.yaml"
  num_classes: 2

  spatial_shape:
    - 2000
    - 2000
    - 120

  max_volume_space:
    - 50
    - 50
    - 2
  min_volume_space:
    - -50
    - -50
    - -4
  seg_labelweights:
    # TODO check if sum below adds up - 0
    # TODO check if sum below adds up - 55437630
    # TODO check if sum below adds up - 320797
    # TODO check if sum below adds up - 541736
    # TODO check if sum below adds up - 2578735
    # TODO check if sum below adds up - 3274484
    # TODO check if sum below adds up - 552662
    # TODO check if sum below adds up - 184064
    # TODO check if sum below adds up - 78858
    # TODO check if sum below adds up - 240942562
    # TODO check if sum below adds up - 17294618
    # TODO check if sum below adds up - 170599734
    # TODO check if sum below adds up - 6369672
    # TODO check if sum below adds up - 230413074
    # TODO check if sum below adds up - 101130274
    # TODO check if sum below adds up - 476491114
    # TODO check if sum below adds up - 9833174
    # TODO check if sum below adds up - 129609852
    # TODO check if sum below adds up - 4506626
    # TODO check if sum below adds up - 1168181
    - 564816438 # Sum of original counts for classes [9,10,11,12,17]
    - 886511409 # Sum of original counts for classes [1-8,13-16,18,19]

  train_data_loader:
    data_path: "./dataset/SemanticKitti/sequences/"
    imageset: "train"
    batch_size: 6
    num_workers: 6
    rotate_aug: False
    flip_aug: False
    scale_aug: False
    transform_aug: False
    dropout_aug: False
    polarmix_aug: False
    mix_aug: False
    instance_aug: False
    d_point_num: 80000

  val_data_loader:
    data_path: "./dataset/SemanticKitti/sequences/"
    num_workers: 12
    imageset: "val"
    batch_size: 12
    rotate_aug: False
    flip_aug: False
    scale_aug: False
    transform_aug: False
    dropout_aug: False
    polarmix_aug: False
    mix_aug: False
    d_point_num: -1

###################
## Train params
train_params:
  seed: 1588147245
  max_num_epochs: 30
  learning_rate: 0.002
  optimizer: AdamW # [SGD, Adam, AdamW]
  lr_scheduler: StepLR # [StepLR, ReduceLROnPlateau, CosineAnnealingLR, CosineAnnealingWarmRestarts]
  momentum: 0.9
  weight_decay: 1.0e-4
  nesterov: True
  lambda_lovasz: 1
  decay_step: 1
  decay_rate: 0.5
  eval_every_n_steps: 200 # 99 #683 #597 #1195
  distributed: False
  amp_enabled: False

###################
## Sparse params
sparse_params:
  use_sparse: True
  growth: "random"
  prune: "magnitude"
  redistribution: "none"
  prune_rate: 0.3
  sparsity: 0.3
  sparse_init: "ERK"
  update_frequency: 8000
  stop_sparse_epoch: 0
